### ISSUE TITLE
CanCOGeN template: Update to order of fields reported in LIMS export 

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#205]
From the CanCOGeN template, the LIMS export reports fields that are present in the NML LIMS in all caps and before the DH provenance field. The fields in lowercase that come after the DH provenance field are strictly captured as-is from the DH (i.e. not changed for LIMS).

The order of the fields helps the NML folks integrate data into LIMS.

They have recently asked us to update some fields in the LIMS export which would necessitate some small changes in the order in which the fields appear in the export.

Can we please report PH_DEHOSTING_METHOD and PH_BIOINFORMATICS_PROTOCOL after PH_CONSENSUS_SEQUENCE_VERSION?
And can we please report PH_INSTRUMENT_CGN after PH_REASON_FOR_SEQUENCING_DETAILS?
And can we please report PH_SAMPLING_DETAILS after HC_SAMPLE_CATEGORY?

Thanks!

**Comment by ddooley** [comment]
Done in latest draft!  It will be in next release when we mint one.

**Comment by griffie** [comment]
I see that "bioinformatics protocol" is still showing up in the LIMS export (last field in lowercase). It's mapped to PH_BIOINFORMATICS_PROTOCOL and is also showing up as that in the export (so it's there twice). Can we remove bioinformatics protocol?
